# Generated by Django 4.2.2 on 2023-06-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_code_smscode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='user',
        ),
    ]
