# Generated by Django 4.2.2 on 2023-06-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_smscode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dispatch_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
