# Generated by Django 4.2.2 on 2023-06-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_dispatch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dispatch_id',
        ),
    ]
