# Generated by Django 4.2.2 on 2023-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_dispatch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dispatch_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
