# Generated by Django 4.2.2 on 2023-06-27 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_dispatch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sms_codes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
