# Generated by Django 4.2.2 on 2023-06-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_smscode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='user',
        ),
    ]
