# Generated by Django 4.2.2 on 2023-06-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.BigIntegerField()),
                ('due_date', models.IntegerField()),
            ],
            options={
                'db_table': 'finance_cards',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.card')),
            ],
            options={
                'db_table': 'finance_payments',
            },
        ),
    ]
