# Generated by Django 4.1.3 on 2023-06-20 08:20

from django.db import migrations
import main.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_plant_farmer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location",
            field=main.utils.fields.LocationField(blank=True, max_length=255),
        ),
    ]
