# Generated by Django 4.2.2 on 2023-06-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_latitude_remove_order_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In_order', 'In_Order'), ('Done', 'Done')], default='Created', max_length=255),
        ),
    ]
